apiVersion: v1
kind: Namespace
metadata:
  name: lab-final-userx
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: lab-final-userx
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: demo
  MONGO_INITDB_ROOT_PASSWORD: demoMX2022!
  MONGO_INITDB_DATABASE: inventorydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: lab-final-userx
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0.8
        envFrom:
          - secretRef:
              name: mongo-creds
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: lab-final-userx
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
